database_type: postgres
database_username: $POSTGRES_USER
database_password: $POSTGRES_PASSWORD
database_host: integration_database
database_port: 5432
database_name: fraud_analysis_integration
database_migration_dir: persistence/migrationDb/schema
database_table: migration
