CREATE TABLE fraud_transaction (
    batch_id VARCHAR(255) ,
    processed_time timestamp,
    transaction_id VARCHAR(255) ,
    customer_id VARCHAR(255),
    card_number BIGINT,
    timestamp TIMESTAMPTZ,
    merchant_category VARCHAR(255),
    merchant_type VARCHAR(255),
    merchant VARCHAR(255),
    amount NUMERIC(15, 2),
    currency VARCHAR(3),
    country VARCHAR(255),
    city VARCHAR(255),
    city_size VARCHAR(50),
    card_type VARCHAR(50),
    card_present BOOLEAN,
    device VARCHAR(255),
    channel VARCHAR(255),
    device_fingerprint VARCHAR(255),
    ip_address INET,
    distance_from_home INT,
    high_risk_merchant BOOLEAN,
    transaction_hour INT,
    weekend_transaction BOOLEAN,
    velocity_last_hour VARCHAR(255),
    is_fraud BOOLEAN
);


